# Generated by Django 2.2.19 on 2021-04-23 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(null=True, upload_to='post/pictures', verbose_name='Trailer'),
        ),
    ]
