# Generated by Django 2.2.19 on 2021-05-19 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
