# Generated by Django 2.2.19 on 2021-06-15 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_post_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imagen2',
            field=models.ImageField(blank=True, null=True, upload_to='post/pictures'),
        ),
    ]
